build_requires: {}
conflicts: {}
dist_name: exiftool.exe
distribution_type: par
dynamic_config: 0
generated_by: 'PAR::Packer version 0.12
license: unknown
par:
  clean: 0
  signature: ''
  verbatim: 0
  version: 1.002
